2019-09-27 20:42:11,366 INFO: Microblog startup [in /home/kibet/Documents/microblog/app/__init__.py:42]
2019-09-27 21:27:14,543 INFO: Microblog startup [in /home/kibet/Documents/microblog/app/__init__.py:42]
2019-09-28 12:36:12,888 INFO: Microblog startup [in /home/kibet/Documents/microblog/app/__init__.py:42]
2019-09-28 12:36:25,011 INFO: Microblog startup [in /home/kibet/Documents/microblog/app/__init__.py:42]
2019-09-29 12:17:38,071 INFO: Microblog startup [in /home/kibet/Documents/microblog/app/__init__.py:42]
2019-09-29 12:19:46,079 INFO: Microblog startup [in /home/kibet/Documents/microblog/app/__init__.py:42]
2019-09-29 12:45:33,907 INFO: Microblog startup [in /home/kibet/Documents/microblog/app/__init__.py:42]
2019-09-29 14:21:00,578 INFO: Microblog startup [in /home/kibet/Documents/microblog/app/__init__.py:42]
2019-09-29 16:42:29,465 INFO: Microblog startup [in /home/kibet/Documents/microblog/app/__init__.py:42]
2019-09-29 16:51:46,176 INFO: Microblog startup [in /home/kibet/Documents/microblog/app/__init__.py:42]
2019-09-29 17:07:32,271 INFO: Microblog startup [in /home/kibet/Documents/microblog/app/__init__.py:42]
2019-09-29 17:11:45,231 INFO: Microblog startup [in /home/kibet/Documents/microblog/app/__init__.py:42]
2019-09-29 17:11:46,864 ERROR: Exception on /index [GET] [in /home/kibet/Documents/microblog/venv/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/kibet/Documents/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kibet/Documents/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kibet/Documents/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/kibet/Documents/microblog/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/kibet/Documents/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kibet/Documents/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/kibet/Documents/microblog/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/kibet/Documents/microblog/app/routes.py", line 29, in index
    return render_template('index.html', title='Home', posts=posts)
  File "/home/kibet/Documents/microblog/venv/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/kibet/Documents/microblog/venv/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/kibet/Documents/microblog/venv/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/kibet/Documents/microblog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/kibet/Documents/microblog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/kibet/Documents/microblog/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/kibet/Documents/microblog/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/kibet/Documents/microblog/app/templates/base.html", line 32, in top-level template code
    {% block content %} {% endblock %}
  File "/home/kibet/Documents/microblog/app/templates/index.html", line 7, in block "content"
    {{ form.hidden_tag() }}
  File "/home/kibet/Documents/microblog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2019-09-29 17:17:54,719 INFO: Microblog startup [in /home/kibet/Documents/microblog/app/__init__.py:42]
2019-09-29 17:36:58,244 INFO: Microblog startup [in /home/kibet/Documents/microblog/app/__init__.py:42]
2019-09-29 17:37:06,177 ERROR: Exception on /index [GET] [in /home/kibet/Documents/microblog/venv/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/kibet/Documents/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kibet/Documents/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kibet/Documents/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/kibet/Documents/microblog/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/kibet/Documents/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kibet/Documents/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/kibet/Documents/microblog/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/kibet/Documents/microblog/app/routes.py", line 28, in index
    page = request.remote_addr.get('page', 1, type=int)
AttributeError: 'str' object has no attribute 'get'
2019-09-29 17:38:11,729 INFO: Microblog startup [in /home/kibet/Documents/microblog/app/__init__.py:42]
2019-09-29 18:01:38,488 INFO: Microblog startup [in /home/kibet/Documents/microblog/app/__init__.py:42]
2019-09-29 18:13:20,919 INFO: Microblog startup [in /home/kibet/Documents/microblog/app/__init__.py:42]
2019-09-29 18:43:57,340 INFO: Microblog startup [in /home/kibet/Documents/microblog/app/__init__.py:44]
2019-09-29 19:03:12,899 INFO: Microblog startup [in /home/kibet/Documents/microblog/app/__init__.py:44]
2019-09-29 19:23:00,666 INFO: Microblog startup [in /home/kibet/Documents/microblog/app/__init__.py:44]
2019-09-30 07:19:14,517 INFO: Microblog startup [in /home/kibet/Documents/microblog/app/__init__.py:44]
2019-09-30 07:19:59,888 ERROR: Exception on /unfollow/c [GET] [in /home/kibet/Documents/microblog/venv/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/kibet/Documents/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kibet/Documents/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kibet/Documents/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/kibet/Documents/microblog/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/kibet/Documents/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kibet/Documents/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/kibet/Documents/microblog/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/kibet/Documents/microblog/app/routes.py", line 129, in unfollow
    current_user.unfollow(user)
  File "/home/kibet/Documents/microblog/app/models.py", line 47, in unfollow
    if self.is_following(user):
  File "/home/kibet/Documents/microblog/app/models.py", line 52, in is_following
    followers.c.followed_id == user.id).count() > 0
AttributeError: 'function' object has no attribute 'id'
2019-10-02 06:19:00,354 INFO: Microblog startup [in /home/kibet/Documents/microblog/app/__init__.py:44]
2019-10-02 06:19:19,033 ERROR: Exception on /unfollow/c [GET] [in /home/kibet/Documents/microblog/venv/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/kibet/Documents/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kibet/Documents/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kibet/Documents/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/kibet/Documents/microblog/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/kibet/Documents/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kibet/Documents/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/kibet/Documents/microblog/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/kibet/Documents/microblog/app/routes.py", line 129, in unfollow
    current_user.unfollow(user)
  File "/home/kibet/Documents/microblog/app/models.py", line 47, in unfollow
    if self.is_following(user):
  File "/home/kibet/Documents/microblog/app/models.py", line 52, in is_following
    followers.c.followed_id == user.id).count() > 0
AttributeError: 'function' object has no attribute 'id'
2019-10-02 06:28:31,596 INFO: Microblog startup [in /home/kibet/Documents/microblog/app/__init__.py:44]
