2019-10-02 06:28:41,156 ERROR: Exception on /unfollow/c [GET] [in /home/kibet/Documents/microblog/venv/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/kibet/Documents/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kibet/Documents/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kibet/Documents/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/kibet/Documents/microblog/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/kibet/Documents/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kibet/Documents/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/kibet/Documents/microblog/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/kibet/Documents/microblog/app/routes.py", line 130, in unfollow
    current_user.unfollow(user)
  File "/home/kibet/Documents/microblog/app/models.py", line 47, in unfollow
    if self.is_following(user):
  File "/home/kibet/Documents/microblog/app/models.py", line 52, in is_following
    followers.c.followed_id == user.id).count() > 0
AttributeError: 'BaseQuery' object has no attribute 'id'
2019-10-03 19:40:44,224 INFO: Microblog startup [in /home/kibet/Documents/microblog/app/__init__.py:44]
2019-10-03 19:40:53,497 ERROR: Exception on /unfollow/a [GET] [in /home/kibet/Documents/microblog/venv/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/kibet/Documents/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kibet/Documents/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kibet/Documents/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/kibet/Documents/microblog/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/kibet/Documents/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kibet/Documents/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/kibet/Documents/microblog/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/kibet/Documents/microblog/app/routes.py", line 130, in unfollow
    current_user.unfollow(user)
  File "/home/kibet/Documents/microblog/app/models.py", line 47, in unfollow
    if self.is_following(user):
  File "/home/kibet/Documents/microblog/app/models.py", line 52, in is_following
    followers.c.followed_id == user.id).count() > 0
AttributeError: 'BaseQuery' object has no attribute 'id'
2019-10-03 19:46:31,140 INFO: Microblog startup [in /home/kibet/Documents/microblog/app/__init__.py:44]
2019-10-03 19:46:40,384 ERROR: Exception on /unfollow/a [GET] [in /home/kibet/Documents/microblog/venv/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/kibet/Documents/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kibet/Documents/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kibet/Documents/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/kibet/Documents/microblog/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/kibet/Documents/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kibet/Documents/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/kibet/Documents/microblog/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/kibet/Documents/microblog/app/routes.py", line 130, in unfollow
    current_user.unfollow(user)
  File "/home/kibet/Documents/microblog/app/models.py", line 46, in unfollow
    if self.is_following(user):
  File "/home/kibet/Documents/microblog/app/models.py", line 51, in is_following
    followers.c.followed_id == user.id).count() > 0
AttributeError: 'BaseQuery' object has no attribute 'id'
2019-10-03 19:49:39,521 INFO: Microblog startup [in /home/kibet/Documents/microblog/app/__init__.py:44]
2019-10-03 19:49:49,555 ERROR: Exception on /unfollow/a [GET] [in /home/kibet/Documents/microblog/venv/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/kibet/Documents/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kibet/Documents/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kibet/Documents/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/kibet/Documents/microblog/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/kibet/Documents/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kibet/Documents/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/kibet/Documents/microblog/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/kibet/Documents/microblog/app/routes.py", line 130, in unfollow
    current_user.unfollow(user)
  File "/home/kibet/Documents/microblog/app/models.py", line 46, in unfollow
    if self.is_following(user):
  File "/home/kibet/Documents/microblog/app/models.py", line 51, in is_following
    followers.c.followed_id == user.id).count() > 0
AttributeError: 'BaseQuery' object has no attribute 'id'
2019-10-03 19:51:49,213 INFO: Microblog startup [in /home/kibet/Documents/microblog/app/__init__.py:44]
2019-10-03 19:55:37,576 INFO: Microblog startup [in /home/kibet/Documents/microblog/app/__init__.py:44]
2019-10-03 20:25:25,870 INFO: Microblog startup [in /home/kibet/Documents/microblog/app/__init__.py:44]
